Repository bmuschko/gradle-docker-plugin, pull requests merged in 2018-10, with the labels that each got.

#663 Move release notes to user guide
  RELEASE_NOTES.md
  gradle/publishing.gradle
  src/docs/asciidoc/50-changes.adoc
  src/docs/asciidoc/index.adoc
Labels: documentation

#664 Use latest Docker CE version
  .travis.yml
Labels: enhancement

#668 Introduce method for translating username/password into a PasswordCredentials
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerRegistryCredentials.groovy
Labels: enhancement

#667 Switch build to Kotlin DSL
  build.gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/AdditionalArtifactsPlugin.kt
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/DocumentationPlugin.kt
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/FunctionalTestPlugin.kt
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/IntegrationTestPlugin.kt
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/PublishingPlugin.kt
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/ReleasePlugin.kt
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/StaticCodeAnalysisPlugin.kt
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/TestSetupPlugin.kt
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/UserGuidePlugin.kt
  gradle/additional-artifacts.gradle
  gradle/asciidoc.gradle
  gradle/codenarc.gradle
  gradle/documentation.gradle
  gradle/functional-test.gradle
  gradle/integration-test.gradle
  gradle/publishing.gradle
  gradle/release.gradle
  gradle/test-setup.gradle
  settings.gradle
  settings.gradle.kts
Labels: enhancement

#672 Make task incremental and cacheable
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy
Labels: enhancement

#678 Use appropriate types for Groovy/Kotlin DSL interoperability for reactive streams functionality
  src/docTest/groovy/com/bmuschko/gradle/docker/RemoteApiPluginDocumentationTest.groovy
  src/docs/asciidoc/14-reactive-streams.adoc
  src/docs/samples/code/remote-api-plugin/reactive-streams/kotlin/build.gradle.kts
  src/docs/samples/code/remote-api-plugin/reactive-streams/kotlin/settings.gradle.kts
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainerFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/DockerClient.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/DockerInfo.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCopyFileFromContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerInspectContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerInspectExecContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerLogsContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerWaitContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerWaitHealthyContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerCommitImage.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerInspectImage.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerListImages.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPullImage.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/network/DockerCreateNetwork.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/network/DockerInspectNetwork.groovy
  src/main/groovy/com/bmuschko/gradle/docker/utils/DockerThreadContextClassLoader.groovy
  src/main/groovy/com/bmuschko/gradle/docker/utils/ThreadContextClassLoader.groovy
Labels: enhancement

#680 Remove CodeNarc verification
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/StaticCodeAnalysisPlugin.kt
  config/codenarc/rules.groovy
Labels: enhancement

#687 Returned image ID for a DockerBuildImage task should never be null
  src/functTest/groovy/com/bmuschko/gradle/docker/AbstractGroovyDslFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy
Labels: bug

#690 Make taskPath safe for windows before using it
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy
Labels: bug, enhancement
