Repository bmuschko/gradle-docker-plugin, pull requests merged in 2018-07, with the labels that each got.

#610 Minor bug-fix/annoyance that our users hit when applying this project to sub-projects...
  src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy
Labels: bug, enhancement

#609 Provide a better experience for setting environment variables.
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerCreateContainerFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy
Labels: enhancement

#611 Various refactorings around use of word probe
  README.asciidoc
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerExecStopFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerLivenessProbeFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/domain/ExecProbe.groovy
  src/main/groovy/com/bmuschko/gradle/docker/domain/LivenessProbe.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerExecStopContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerLivenessContainer.groovy
Labels: enhancement

#616 Shade cglib and its dependencies.
  src/functTest/groovy/com/bmuschko/gradle/docker/AbstractDockerRemoteApiTaskFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.groovy
  src/main/groovy/com/bmuschko/gradle/docker/utils/DockerThreadContextClassLoader.groovy
Labels: enhancement

#619 Initial support for dockerized Spring Boot applications
  README.asciidoc
  src/functTest/groovy/com/bmuschko/gradle/docker/AbstractFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplicationPluginFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerfileFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerExtension.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplication.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplicationPlugin.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractReactiveStreamsTask.groovy
  src/main/resources/META-INF/gradle-plugins/com.bmuschko.docker-spring-boot-application.properties
Labels: enhancement

#627 Provide links to external APIs so that Groovydocs can create connection
  gradle/documentation.gradle
Labels: documentation

#630 Generate and publish user guide written in Asciidoc
  README.adoc
  README.asciidoc
  RELEASE_NOTES.md
  build.gradle
  gradle/asciidoc.gradle
  gradle/documentation.gradle
  src/docs/asciidoc/00-intro.adoc
  src/docs/asciidoc/01-provided-plugins.adoc
  src/docs/asciidoc/02-getting-started.adoc
  src/docs/asciidoc/10-remote-api-plugin.adoc
  src/docs/asciidoc/11-usage.adoc
  src/docs/asciidoc/12-extension.adoc
  src/docs/asciidoc/13-custom-task-types.adoc
  src/docs/asciidoc/14-reactive-streams.adoc
  src/docs/asciidoc/15-examples.adoc
  src/docs/asciidoc/20-java-application-plugin.adoc
  src/docs/asciidoc/21-usage.adoc
  src/docs/asciidoc/22-extension.adoc
  src/docs/asciidoc/23-tasks.adoc
  src/docs/asciidoc/24-examples.adoc
  src/docs/asciidoc/30-spring-boot-application-plugin.adoc
  src/docs/asciidoc/31-usage.adoc
  src/docs/asciidoc/32-extension.adoc
  src/docs/asciidoc/33-tasks.adoc
  src/docs/asciidoc/34-examples.adoc
  src/docs/asciidoc/40-about.adoc
  src/docs/asciidoc/index.adoc
Labels: documentation

#634 On CI the whole test suite should be run
  gradle/test-setup.gradle
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplicationPluginFunctionalTest.groovy
  src/testSetup/groovy/com/bmuschko/gradle/docker/DockerHubCredentials.groovy
  src/testSetup/groovy/com/bmuschko/gradle/docker/TestPrecondition.groovy
Labels: enhancement

#635 Fully deprecate MAINTAINER instruction and replace with LABEL
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPlugin.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy
  src/test/groovy/com/bmuschko/gradle/docker/tasks/image/DockerfileTest.groovy
Labels: enhancement

#636 Use smaller base images for convention plugins
  src/docs/asciidoc/22-extension.adoc
  src/docs/asciidoc/32-extension.adoc
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplicationPluginFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerJavaApplication.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplication.groovy
Labels: enhancement
