Repository bmuschko/gradle-docker-plugin, pull requests merged in 2018-06, with the labels that each got.

#590 DockerExecContainer gained option 'successOnExitCodes' which allows t…
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerExecContainerFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerInspectExecContainer.groovy
Labels: enhancement

#587 Added new task DockerLivenessProbeContainer.
  README.asciidoc
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerLivenessProbeFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/domain/Probe.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerLogsContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerLivenessProbeContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/utils/IOUtils.groovy
Labels: enhancement

#591 Added task DockerExecStopContainer
  README.asciidoc
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerLivenessProbeFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/domain/ExecStopProbe.groovy
  src/main/groovy/com/bmuschko/gradle/docker/domain/LivenessProbe.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerStopContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerExecStopContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerLivenessProbeContainer.groovy
Labels: enhancement

#592 Various minor refactorings to allow for DockerExecStopContainer to be more flexible
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerExecContainerFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerExecStopFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerStopContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerExecStopContainer.groovy
Labels: enhancement

#594 Defining a probe is now optional and if not done will fallback to che…
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerLivenessProbeFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerLogsContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerLivenessProbeContainer.groovy
Labels: enhancement

#595 Explicitly call toString() on values in maps passed to Docker API
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerCreateContainerFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerListImagesFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerListImages.groovy
Labels: bug

#596 DockerLivenessProbeContainer gained method 'lastInspection()' which, …
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerLivenessProbeFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerLivenessProbeContainer.groovy
Labels: enhancement

#600 DockerExecContainer gained option to specify multiple commands to be run
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerExecContainerFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy
Labels: enhancement

#601 Fix logging output to be more generic.
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerExecStopContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerLivenessProbeContainer.groovy
Labels: enhancement

#602 Fix bug in DockerExecContainer where exitCode can be null.
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerExecContainerFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/domain/ExecProbe.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerExecContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/extras/DockerExecStopContainer.groovy
Labels: bug, enhancement
