Repository bmuschko/gradle-docker-plugin, pull requests merged in 2019-04, with the labels that each got.

#777 #766 Only consider .class files when searching for main class
  src/main/groovy/com/bmuschko/gradle/docker/utils/MainClassFinder.groovy
  src/test/groovy/com/bmuschko/gradle/docker/utils/MainClassFinderTest.groovy
Labels: bug, enhancement

#782 Fix Gradle 5.x deprecation warnings
  src/docs/asciidoc/00-intro.adoc
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainerFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerExtension.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCopyFileToContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerListImages.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerLoadImage.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy
Labels: enhancement

#787 Update build.gradle.kts
  build.gradle.kts
Labels: enhancement

#789 Rename timeout properties to waitTime so as not to clobber the exiting timeout property on gradles Task.
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerWorkflowFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerRestartContainer.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerStopContainer.groovy
Labels: bug

#790 Expose extension property for configuring JVM arguments
  src/docs/asciidoc/12-extension.adoc
  src/docs/asciidoc/22-extension.adoc
  src/docs/asciidoc/32-extension.adoc
  src/docs/samples/code/application-plugin/basic/groovy/build.gradle
  src/docs/samples/code/application-plugin/basic/kotlin/build.gradle.kts
  src/docs/samples/code/spring-boot-plugin/basic/groovy/build.gradle
  src/docs/samples/code/spring-boot-plugin/basic/kotlin/build.gradle.kts
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPluginFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplicationPluginFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerExtension.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerJavaApplication.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPlugin.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplication.groovy
  src/main/groovy/com/bmuschko/gradle/docker/DockerSpringBootApplicationPlugin.groovy
Labels: enhancement
