Repository bmuschko/gradle-docker-plugin, pull requests merged in 2021-06, with the labels that each got.

#1012 Bump ASM opcode version.
  src/main/groovy/com/bmuschko/gradle/docker/internal/MainClassFinder.groovy
Labels: enhancement

#1016 Reduce Docker Java dependency size
  build.gradle.kts
  src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy
Labels: enhancement

#1017 Avoid referencing inner classes by fully-qualified class name to ensure compatibility with latest Kotlin version
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerfileFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy
  src/test/groovy/com/bmuschko/gradle/docker/tasks/image/DockerfileTest.groovy
Labels: bug

#1024 Introduce platform parameter for build image task
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerfileFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy
Labels: enhancement

#1025 Upgrade to Docker Java 3.2.10
  build.gradle.kts
Labels: docker-java, enhancement

#1026 Introduce platform parameter for create container task
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy
Labels: docker-java, enhancement
