Repository bmuschko/gradle-docker-plugin, pull requests merged in 2022-08, with the labels that each got.

#1080 Add Ipam configuration for a network
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/network/DockerNetworkFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/network/DockerCreateNetwork.groovy
Labels: enhancement

#1069 Support multiple images for DockerSaveImage (#1067)
  build.gradle.kts
  gradle/libs.versions.toml
  src/functTest/groovy/com/bmuschko/gradle/docker/AbstractFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/DockerWorkflowFunctionalTest.groovy
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerSaveImageFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerSaveImage.groovy
Labels: enhancement

#1081 Close InputStream
  src/main/groovy/com/bmuschko/gradle/docker/internal/MainClassFinder.groovy
Labels: bug

#1083 Proper handling of onNext callbacks in DockerLogsContainer task
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/container/DockerLogsContainerFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerLogsContainer.groovy
Labels: bug

#1073 Make DockerSaveImage out of date if the input state on the daemon changed (#1071)
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerSaveImageFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerSaveImage.groovy
Labels: bug

#1085 Upgrade Asciidoctor plugin to latest version
  .github/workflows/linux-build-release.yml
  .github/workflows/windows-build.yml
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/DocumentationPlugin.kt
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/UserGuidePlugin.kt
  gradle/buildsrc.libs.versions.toml
  src/docs/samples/code/application-plugin/basic/groovy/build.gradle
  src/docs/samples/code/application-plugin/basic/kotlin/build.gradle.kts
  src/docs/samples/code/application-plugin/jetty/groovy/build.gradle
  src/docs/samples/code/application-plugin/jetty/kotlin/build.gradle.kts
  src/docs/samples/code/remote-api-plugin/apply-plugin-buildscript/groovy/build.gradle
  src/docs/samples/code/remote-api-plugin/apply-plugin-buildscript/kotlin/build.gradle.kts
  src/docs/samples/code/remote-api-plugin/apply-plugin-dsl/groovy/build.gradle
  src/docs/samples/code/remote-api-plugin/apply-plugin-dsl/kotlin/build.gradle.kts
  src/docs/samples/code/remote-api-plugin/apply-plugin-from-script-plugin/groovy/gradle/docker.gradle
  src/docs/samples/code/remote-api-plugin/basic/groovy/build.gradle
  src/docs/samples/code/remote-api-plugin/basic/kotlin/build.gradle.kts
  src/docs/samples/code/remote-api-plugin/build-image/groovy/build.gradle
  src/docs/samples/code/remote-api-plugin/build-image/kotlin/build.gradle.kts
  src/docs/samples/code/remote-api-plugin/custom-task-type/groovy/build.gradle
  src/docs/samples/code/remote-api-plugin/custom-task-type/kotlin/build.gradle.kts
  src/docs/samples/code/remote-api-plugin/dockerfile-instructions/groovy/build.gradle
  src/docs/samples/code/remote-api-plugin/dockerfile-instructions/kotlin/build.gradle.kts
  src/docs/samples/code/remote-api-plugin/functional-test/groovy/build.gradle
  src/docs/samples/code/remote-api-plugin/functional-test/kotlin/build.gradle.kts
  src/docs/samples/code/remote-api-plugin/linking-containers/groovy/build.gradle
  src/docs/samples/code/remote-api-plugin/linking-containers/kotlin/build.gradle.kts
  src/docs/samples/code/remote-api-plugin/reactive-streams/groovy/build.gradle
  src/docs/samples/code/remote-api-plugin/reactive-streams/kotlin/build.gradle.kts
  src/docs/samples/code/spring-boot-plugin/basic/groovy/build.gradle
  src/docs/samples/code/spring-boot-plugin/basic/kotlin/build.gradle.kts
  src/docs/samples/code/spring-boot-plugin/tomcat/groovy/build.gradle
  src/docs/samples/code/spring-boot-plugin/tomcat/kotlin/build.gradle.kts
Labels: bug

#1089 Split end user and developer guides
  .github/workflows/linux-build-release.yml
  .github/workflows/windows-build.yml
  README.adoc
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/DocumentationPlugin.kt
  buildSrc/src/main/kotlin/com/bmuschko/gradle/docker/UserGuidePlugin.kt
  src/docs/asciidoc/dev-guide/10-about.adoc
  src/docs/asciidoc/dev-guide/20-development.adoc
  src/docs/asciidoc/dev-guide/30-release-process.adoc
  src/docs/asciidoc/dev-guide/index.adoc
  src/docs/asciidoc/user-guide/00-intro.adoc
  src/docs/asciidoc/user-guide/01-provided-plugins.adoc
  src/docs/asciidoc/user-guide/02-getting-started.adoc
  src/docs/asciidoc/user-guide/10-remote-api-plugin.adoc
  src/docs/asciidoc/user-guide/11-usage.adoc
  src/docs/asciidoc/user-guide/12-extension.adoc
  src/docs/asciidoc/user-guide/13-custom-task-types.adoc
  src/docs/asciidoc/user-guide/14-reactive-streams.adoc
  src/docs/asciidoc/user-guide/15-examples.adoc
  src/docs/asciidoc/user-guide/20-java-application-plugin.adoc
  src/docs/asciidoc/user-guide/21-usage.adoc
  src/docs/asciidoc/user-guide/22-extension.adoc
  src/docs/asciidoc/user-guide/23-tasks.adoc
  src/docs/asciidoc/user-guide/24-dockerfile.adoc
  src/docs/asciidoc/user-guide/25-examples.adoc
  src/docs/asciidoc/user-guide/30-spring-boot-application-plugin.adoc
  src/docs/asciidoc/user-guide/31-usage.adoc
  src/docs/asciidoc/user-guide/32-extension.adoc
  src/docs/asciidoc/user-guide/33-tasks.adoc
  src/docs/asciidoc/user-guide/34-dockerfile.adoc
  src/docs/asciidoc/user-guide/35-examples.adoc
  src/docs/asciidoc/user-guide/40-changes.adoc
  src/docs/asciidoc/user-guide/index.adoc
Labels: documentation

#1088 Tweak DockerCreateContainerFunctionalTest
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainerFunctionalTest.groovy
Labels: enhancement

#1087 Add "add" and "drop" host config capability to DockerCreateContainer task
  src/functTest/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainerFunctionalTest.groovy
  src/main/groovy/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.groovy
Labels: enhancement
