Repository bmuschko/gradle-docker-plugin, pull requests merged in 2023-10, with the labels that each got.

#1196 Credentials provided by extension need to override credentials in store
  src/main/java/com/bmuschko/gradle/docker/internal/RegistryAuthLocator.java
  src/test/groovy/com/bmuschko/gradle/docker/internal/RegistryAuthLocatorTest.groovy
Labels: bug

#1198 Minor improvement to CI/CD pipeline
  .github/workflows/linux-build-release.yml
Labels: enhancement

#1199 Upgrade to Docker Java 3.3.3
  gradle/libs.versions.toml
Labels: enhancement, docker-java

#1200 Upgrade ASM to 9.6
  gradle/libs.versions.toml
Labels: enhancement
